name: CICDJAVA

on:  
  push:  
    branches-ignore: [ develop, staging ]    

  pull_request:  
    branches: [ develop, staging ]

  release:
    types: [ created ]

  workflow_dispatch:

env:
  GITHUB_CONTEXT: ${{ toJson(github) }}

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Compile
        run: echo ${{ github.release.target_commitish }} ${{ github.event_name }} - ${{ github.base_ref }} - ${{ github.ref }} - ${{ github.event.pull_request.merged }} - ${{ github.event.action }} $GITHUB_CONTEXT - Compile Step..
    
  DeployDev:
    name: Deploy to Dev 
    if: github.event_name == 'pull_request' && github.base_ref == 'develop'
    needs: [Build]
    runs-on: ubuntu-latest
    environment: 
      name: Development
      url: 'http://someweb.com'
    steps:
      - name: Deploy
        run: echo Deploying Dev....   
    
  DeployPreproduction:
    name: Deploy to Preproduction 
    needs: [Build]
    if: github.event_name == 'pull_request' && github.base_ref == 'staging'
    runs-on: ubuntu-latest
    environment: 
      name: Preproduction
      url: 'http://someweb.com'
    steps:
      - name: Tagging to Staging Branch        
        run: |
            deploymentTag=$(date +'v%Y.%m.%d.%H%M')
            echo "$deploymentTag"   
            git config --global user.email "generic_action@github.com"
            git config --global user.name "generic_action"
            git fetch
            git checkout -f --track -B staging remotes/origin/staging --
            git pull --progress -v --no-rebase --no-ff "origin"
            git tag -a $deploymentTag -m "Deployment done to staging with id: $deploymentTag" 
            echo "Tag creado: $deploymentTag"  
            git push --tags --progress "origin" staging:staging
            echo "Push creado con el tag: $deploymentTag"

      - name: Deploy
        run: echo I am deploying!!!
            
  DeployProduction:
    name: Deploy to Production 
    if: github.event_name == 'release'
    needs: [Build]
    runs-on: ubuntu-latest
    environment: 
      name: Production
      url: 'http://someweb.com'
    steps:
      - name: Deploy
        run: echo I am deploying! 
    env:
        CI: true
